#ifndef AVS_ANPR_H
#define AVS_ANPR_H

#define AVS_DEBUG_MODE_DISPLAY_SOURCE    0
#define AVS_DEBUG_MODE_DISPLAY_SOBEL     1
#define AVS_DEBUG_MODE_DISPLAY_MORPH     2
#define AVS_DEBUG_MODE_DISPLAY_DEBUGGING 3

#endif // AVS_ANPR_H
